import os
import time
from pathlib import Path
import numpy as np

# MetalloGen imports
from MetalloGen import globalvars as gv
from MetalloGen import om, embed, clean_geometry
from MetalloGen.utils import clustering
from rdkit import Chem

def clean_working_directory(working_directory):
    """Cleans up scratch files generated by quantum chemical calculators."""
    if not working_directory:
        return
        
    wd = Path(working_directory)
    if not wd.exists():
        return
        
    wildcard_patterns = ["Gau-*"]
    file_names = ['energy', 'gradient', 'xtb', 'charges', 'xtbrestart', 'xtbtopo.mol']
    
    for pattern in wildcard_patterns:
        for file in wd.glob(pattern):
            if file.is_file():
                file.unlink()

    for filename in file_names:
        file = wd / filename
        if file.exists() and file.is_file():
            file.unlink()


class TMCGenerator:
    """Helper class to generate and initially scan conformers."""
    
    def __init__(self, calculator, scale=1.0, align=True, always_qc=False):
        self.cleaner = clean_geometry.TMCOptimizer(calculator=calculator)
        self.calculator = calculator
        self.scale = scale
        self.corrector = 0.2
        self.align = align
        self.always_qc = always_qc

    def sample_conformer(self, metal_complex, return_time=False):
        options = [0, 1]
        candidate_positions = []
        candidate_list = []
        energy_list = []
        
        gen_time_list = []
        scan_time_list = []
        gen_times = []
        scan_times = []
        
        for idx, option in enumerate(options):
            print(f"Embedding molecule {idx+1}/{len(options)} ...")
            gen_st = time.time()
            positions = embed.get_embedding(metal_complex, self.scale, option, self.align, use_random=True)
            if positions is not None:
                gen_et = time.time()
                candidate_positions.append(positions)
                gen_time_list.append(gen_et - gen_st)

        # Clean geometry and compute energy for each candidate position
        for candidate_position in candidate_positions:
            scan_st = time.time()
            tmp_metal_complex = metal_complex.copy()
            tmp_metal_complex.set_position(candidate_position)
            
            # Geometry optimization
            success = self.cleaner.clean_geometry(tmp_metal_complex, self.scale, self.always_qc) 
            scan_et = time.time()
            scan_time_list.append(scan_et - scan_st)
            
            ace_mol = tmp_metal_complex.get_molecule()
            energy = None

            candidate_list.append(ace_mol)
            # Temporarily remove the try/except to see the raw error
            print(f"Attempting xTB energy calculation for conformer...")
            energy = self.calculator.get_energy(ace_mol)

            # candidate_list.append(ace_mol)
            # try:
            #     energy = self.calculator.get_energy(ace_mol)
            # except Exception:
            #     energy = None
            #     scan_time_list[-1] = -1
                
            energy_list.append(energy if energy is not None else 1e6)

        print('energy', energy_list, '\n')
        
        if len(energy_list) == 0 or min(energy_list) == 1e6:
            return ([], [], []) if return_time else []
            
        # Use the most stable positions
        indices = np.argsort(energy_list)
        ace_mols = []
        for i in indices:
            if energy_list[i] < 1e6:
                candidate_list[i].energy = energy_list[i]
                ace_mols.append(candidate_list[i])
                gen_times.append(gen_time_list[i])
                scan_times.append(scan_time_list[i])

        return (ace_mols, gen_times, scan_times) if return_time else ace_mols


class MetallogenInterface:
    """Main interface for programmatic access to MetalloGen 3D generation."""

    def __init__(self, 
                 working_directory="./scratch", 
                 save_directory="./output", 
                 final_relax=True, 
                 num_conformer=10, 
                 calculator_type="xtb"):
        
        self.working_directory = working_directory
        self.save_directory = save_directory
        self.final_relax = final_relax
        self.num_conformer = num_conformer
        self.calculator_type = calculator_type.lower()
        
        self._setup_directories()
        self.calculator = self._initialize_calculator()

    def _setup_directories(self):
        """Creates required directories if they don't exist."""
        if self.save_directory:
            os.makedirs(self.save_directory, exist_ok=True)
        if self.working_directory:
            os.makedirs(self.working_directory, exist_ok=True)

    def _initialize_calculator(self):
        """Initializes the requested quantum chemical calculator dynamically."""
        if self.calculator_type == "xtb_gaussian":
            from MetalloGen.Calculator import gaussian
            calc = gaussian.Gaussian()
            calc.switch_to_xtb_gaussian()
            
        elif self.calculator_type == "xtb":
            from MetalloGen.Calculator import xtb
            calc = xtb.XTB()

        elif self.calculator_type == "xtb_s":
            from MetalloGen.Calculator import xtb_s
            calc = xtb_s.XTB_Standalone()

        elif self.calculator_type == "orca":
            from MetalloGen.Calculator import orca
            calc = orca.Orca()
            
        elif self.calculator_type == "gaussian":
            from MetalloGen.Calculator import gaussian
            calc = gaussian.Gaussian()
            
        else:
            raise ValueError(f"Invalid calculator specified: {self.calculator_type}")
            
        if self.working_directory:
            calc.change_working_directory(self.working_directory)
            
        return calc
    
    # def save_with_connectivity(self, ace_mol, filename):
    #     """Saves the conformer with explicit bonds using RDKit or MetalloGen's internal mapper."""
    #     # MetalloGen's ace_mol often has an internal graph. 
    #     # If it supports RDKit conversion:
    #     rd_mol = ace_mol.to_rdkit() # Check if your version of MetalloGen has this
        
    #     if rd_mol:
    #         # Save as SDF which preserves the bond table
    #         writer = Chem.SDWriter(os.path.join(self.save_directory, f"{filename}.sdf"))
    #         writer.write(rd_mol)
    #         writer.close()
    #     else:
    #         # Fallback: Use OpenBabel internally if installed
    #         import subprocess
    #         xyz_path = os.path.join(self.save_directory, f"{filename}.xyz")
    #         mol2_path = os.path.join(self.save_directory, f"{filename}.mol2")
    #         # This uses OpenBabel to 'infer' bonds and write a mol2
    #         subprocess.run(["obabel", xyz_path, "-O", mol2_path])

    def generate(self, smiles=None, input_directory=None):
        """
        Generates 3D structures for an organometallic complex.
        
        Provide EITHER a valid MSMILES string OR a path to an SDF/MOL input directory.
        """
        if smiles and "|" in smiles:
            metal_complex = om.get_om_from_modified_smiles(smiles)
            print(f"Loaded from MSMILES: {smiles}")
        elif input_directory:
            metal_complex = om.get_om_from_sdf(input_directory)
            print(f"Loaded from input directory: {os.path.basename(input_directory)}")
        else:
            raise ValueError("Please provide either a valid MSMILES string or an input MOL/SDF directory.")

        print(f"num atoms: {len(metal_complex.get_atom_list())}")
        print(f"chg: {metal_complex.chg}")
        print(f"mult: {metal_complex.multiplicity}")

        # Determine scaling factors based on requested number of conformers
        if self.num_conformer < 10:
            scales = [0.70, 0.80, 0.90, 1.00, 1.10]
        else:
            scales = [0.7 + ((0.8 + 0.1*(self.num_conformer-10))/(self.num_conformer-2))*k for k in range(int(self.num_conformer/2))]

        # 1. Generate Conformers
        total_ace_mols = []
        for scale in scales:
            print(f"\nGenerating conformer with scale {scale:.2f} ...")
            print("======================================================")
            generator = TMCGenerator(self.calculator, scale, align=True)
            ace_mols = generator.sample_conformer(metal_complex)
            total_ace_mols.extend(ace_mols)

        print("=======================================================")
        print(f"\nTotal {len(total_ace_mols)} conformers generated ...")
        
        if not total_ace_mols:
            print("No valid conformers generated. Exiting early.")
            return []

        # 2. Cluster Conformers
        print(f"\nClustering conformers ...")
        conformers = [ace_mol.get_coordinate_list() for ace_mol in total_ace_mols]
        atom_symbol = [atom.get_element() for atom in metal_complex.get_atom_list()]
        
        clusters, _ = clustering.cluster_conformers_butina(conformers, atom_symbol, cutoff=0.5, exclude_H=True)
        dif_ace_mols = [total_ace_mols[i[0]] for i in clusters]
        print(f"{len(dif_ace_mols)} conformers after clustering ...")

        if not self.final_relax:
            return dif_ace_mols

        # 3. Final Relaxation
        print("\nPerforming final relaxation ...")
        final_relaxed_mols = []
        num_successful = 0
        initial_hessian = None

        for i, ace_mol in enumerate(dif_ace_mols):
            if num_successful >= self.num_conformer:
                break
                
            print(f"\nRelaxing clustered conformer {i+1}/{len(dif_ace_mols)} ...")
            print("======================================================")
            
            original_energy = ace_mol.energy
            if original_energy == 1e6:
                continue
                
            print(f"Initial Energy: {original_energy}")
            
            try:
                # Run optimization
                self.calculator.optimize_geometry(ace_mol, 
                                                  file_name=f"final_relax_{num_successful}", 
                                                  initial_hessian=initial_hessian, 
                                                  save_directory=self.save_directory)
                normal_termination = True
            except Exception as e:
                print(f"Relaxation failed with error: {e}")
                normal_termination = False

            clean_working_directory(self.working_directory)

            if not normal_termination:
                print("Relaxation failed. Skipping to next conformer...")
                continue

            relaxed_energy = getattr(ace_mol, 'energy', 'Unknown')
            print(f"Relaxed Energy: {relaxed_energy}")
            
            # Save to disk
            content = f"{len(ace_mol.atom_list)}\n{ace_mol.chg}\t{ace_mol.multiplicity}\t{relaxed_energy}\n"
            for atom in ace_mol.atom_list:
                content += atom.get_content()

            if self.save_directory:
                file_base = f"result_{num_successful}"
                sdf_path = os.path.join(self.save_directory, f"{file_base}.sdf")
                
                try:
                    from rdkit import Chem
                    from rdkit.Chem import EditableMol, Mol
                    
                    # 1. Start fresh
                    emol = EditableMol(Mol())
                    atoms = ace_mol.get_atom_list()
                    
                    # 2. Add Atoms
                    for atom in atoms:
                        emol.AddAtom(Chem.Atom(atom.get_element()))
                    
                    # 3. Add Bonds from Adjacency Matrix
                    # adj_matrix is a 2D array where matrix[i][j] > 0 means a bond
                    adj = ace_mol.get_adj_matrix()
                    num_atoms = len(atoms)
                    for i in range(num_atoms):
                        for j in range(i + 1, num_atoms):
                            if adj[i][j] > 0:
                                # We use SINGLE to ensure RDKit doesn't crash on metal valency
                                emol.AddBond(i, j, Chem.rdchem.BondType.SINGLE)
                    
                    # 4. Finalize and set coords
                    rd_mol = emol.GetMol()
                    conf = Chem.Conformer(num_atoms)
                    for idx, atom in enumerate(atoms):
                        pos = atom.get_coordinates()
                        conf.SetAtomPosition(idx, (float(pos[0]), float(pos[1]), float(pos[2])))
                    rd_mol.AddConformer(conf)

                    # 5. Write to Disk
                    writer = Chem.SDWriter(sdf_path)
                    writer.write(rd_mol)
                    writer.close()
                    print(f"MANUAL SDF SUCCESS: {sdf_path}")
                        
                except Exception as e:
                    print(f"Manual SDF build failed: {e}. Falling back to XYZ.")
                    # Keep your old XYZ writing code here
                    content = f"{len(ace_mol.atom_list)}\n{ace_mol.chg}\t{ace_mol.multiplicity}\t{relaxed_energy}\n"
                    for atom in ace_mol.atom_list:
                        content += atom.get_content()
                    with open(os.path.join(self.save_directory, f"{file_base}.xyz"), "w") as f:
                        f.write(content)


            print("Relaxation success!\n")
            num_successful += 1
            final_relaxed_mols.append(ace_mol)

        print("=======================================================")
        print(f"\nTotal {num_successful} conformers successfully relaxed and saved.")
        return final_relaxed_mols
    
    def quick_view(self, index=0):
        """Interactive 3D visualization of the result."""
        import py3Dmol
        
        sdf_path = os.path.join(self.save_directory, f"result_{index}.sdf")
        xyz_path = os.path.join(self.save_directory, f"result_{index}.xyz")
        
        if os.path.exists(sdf_path):
            path, fmt = sdf_path, "sdf"
        else:
            path, fmt = xyz_path, "xyz"
            print("Warning: Visualizing XYZ. Bonds are inferred by distance.")

        with open(path, 'r') as f:
            data = f.read()

        view = py3Dmol.view(width=800, height=500)
        view.addModel(data, fmt)
        
        # Style: Stick & Sphere (Professional Look)
        # Note: radius 0.15 and scale 0.25 mimic the image you uploaded
        view.setStyle({'stick': {'radius': 0.15}, 'sphere': {'scale': 0.25}})
        
        # Aesthetic tweaks
        view.setBackgroundColor('#ffffff')
        view.zoomTo()
        return view.show()
    
    